### ISSUE TITLE
Accessing scraped data for gov_uk takes more than 900 seconds.

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/wsf-web-scraper#115]
We were just trying to download all the 100K documents for uk_gov and that query seems to be quite slow so I wonder whether this is an indexing issue or purely the fact that 100K documents with their text in the column makes this retrieval inefficient. Any way we can speed this up?

```SQL
SELECT * FROM publication
WHERE publication.id_provider=5
```

<img width="944" alt="screen shot 2018-10-25 at 5 45 28 pm" src="https://user-images.githubusercontent.com/4975761/47516633-d9b79980-d87d-11e8-931b-a0c46728f87e.png">

**Comment by SamDepardieu** [comment]
@nsorros We went through this I think? Can we close this?

**Comment by nsorros** [comment]
No prob
