### ISSUE TITLE
Keyword sentence content in varying formats

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/wsf-web-scraper#122]
The data field `sentence_content` in publications_keywords has various forms, sometimes they are in curly brackets and sometimes in square:
![screenshot 2019-01-10 at 15 38 37](https://user-images.githubusercontent.com/15956065/50979161-d54e6480-14ed-11e9-8039-7389c3462bb4.png)

We found that the first ~90 rows have square brackets.

It was also found that whilst in most cases the data is in the form `{'string'}` (with square or curly bois), sometimes it is in the form `{string}` (i.e. with no quotes). This causes problems later down the line with reading the data, since we rely on `ast.literal_eval` to convert the `sentence_content` data into a list of strings, so in this example out code fails:
![image](https://user-images.githubusercontent.com/15956065/50979155-d2ec0a80-14ed-11e9-8044-c5d5c5db39a9.png)

**Comment by SamDepardieu** [comment]
This is weird. Will defo check that.
What should be the best output for you @lizgzil ?

**Comment by lizgzil** [comment]
I think {'string'} is best, and {'string','otherstring'} if multiple 🙂

**Comment by SamDepardieu** [comment]
Working on this issue since this morning, everything in the code looks fine, and the only results concerned by this issue in the database seems to come from last July.

**Comment by SamDepardieu** [comment]
Precisely, all `[...]` formatted keywords are coming from a scraper run on July 3rd. I can fix this by replacing the brackets by some curly bois 😄

**Comment by hblanks** [comment]
@SamDepardieu  - can we make sure to track this as unplanned work on the sprint board, please?

**Comment by SamDepardieu** [comment]
I fixed it in the DB. Closing this as the last instance of this happening was in august last year.
