### ISSUE TITLE
Pulling publications from the database into the warehouse leads to an oom

### ISSUE THREAD

**Issue by SamDepardieu** [wellcometrust/wsf-web-scraper#129]

**Comment by SamDepardieu** [comment]
Not saying it's coming from that, but we added 35k publication in the last 3 days

**Comment by SamDepardieu** [comment]
On a `SELECT * FROM ..` type request, the result set of these 35k publications weights about 1.5Go

**Comment by SamDepardieu** [comment]
@lizgzil @nsorros I was wondering, do you really need the full PDF text to be in the database?

**Comment by nsorros** [comment]
No, we need the full PDF somewhere, s3 probably being a better place. @hblanks can comment on this.

**Comment by hblanks** [comment]
@SamDepardieu  - how would one reproduce this bug? Do we have any output or screenshots we can look at?

**Comment by hblanks** [comment]
Tracked now at https://github.com/wellcometrust/datalabs-infra/issues/99 and subsequently https://trello.com/c/aFfSoqxV/553-drop-pdftext-from-publication-table
