### ISSUE TITLE
Create a generic crawling spider

### ISSUE THREAD

**Issue by SamDepardieu** [wellcometrust/wsf-web-scraper#57]
This spider should be able to crawls every given websites, looking for given file types (default to PDF), and convert them (if needed) to a machine-readable format (txt/csv/json...).

**Comment by jdkram** [comment]
![image](https://user-images.githubusercontent.com/235073/38735019-72dbd1f6-3f1f-11e8-9cb4-fa6f3d270dda.png)

**Comment by jdkram** [comment]
![](https://dsc.cloud/jdkram/pb-tiXUhiJHWn.png)
