### ISSUE TITLE
Write a better readme

### ISSUE THREAD

**Issue by SamDepardieu** [wellcometrust/wsf-web-scraper#66]

**Comment by jdkram** [comment]
Happy to help with this one

**Comment by jdkram** [comment]
but spider in README only has 7 legs

**Comment by jdkram** [comment]
![noun_1394672](https://user-images.githubusercontent.com/235073/41777188-6f01860e-7622-11e8-8c40-4146f777cf43.png)

Propose minecraft spider

**Comment by jdkram** [comment]
![noun_1449242 1](https://user-images.githubusercontent.com/235073/41777272-aafbb1fc-7622-11e8-9dec-ccb793266e4d.png)
![noun_235530](https://user-images.githubusercontent.com/235073/41777273-ab17d8c8-7622-11e8-8781-3b685a0b1f09.png)
![noun_1394672](https://user-images.githubusercontent.com/235073/41777275-ab32ba08-7622-11e8-8b3b-524e4728e0f2.png)

**Comment by SamDepardieu** [comment]
But I like it, it looks so happy 🙂

**Comment by jdkram** [comment]
You're right. I'm being prejudiced and I am sorry.
