### ISSUE TITLE
Item['pdf'] is not obvious that contains the filename of the pdf

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/wsf-web-scraper#82]
I thought this contained the content of the pdf. It is worth considering an alternative name or asking for second opinion (maybe it was just unclear to me)

**Comment by SamDepardieu** [comment]
I can change it. Do you want me to save the full pdf text as well? If so we might want to consider another storage method, as it will lead to pretty big json files

**Comment by nsorros** [comment]
Yes we do need to start saving the entire text but we should discuss what is the best way to persist that i agree.

**Comment by SamDepardieu** [comment]
We now have a `pdf_text` field containing the whole PDF
