### ISSUE TITLE
Keyword match returns no associated text

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/wsf-web-scraper#92]
Sometimes a keyword matches but there is no associated text from which the match was pulled.

SQL to see examples
```
select
	keyword.name,
	text_content
from publications_keywords
inner join keyword on keyword.id=publications_keywords.id_keyword
where name='gavi'
```

Screenshot of results 
<img width="511" alt="screen shot 2018-08-15 at 11 36 32 am" src="https://user-images.githubusercontent.com/4975761/44144542-dd409e48-a07f-11e8-98f6-3ca373907866.png">

**Comment by SamDepardieu** [comment]
This seems to be fine now, could you check again on your side @nsorros ?

**Comment by nsorros** [comment]
Yep all good, no empty rows that i could find
